import { MoveControls, ImportMoves } from './MoveControls';
import { moveScore, type MoveRow } from '@/modules/strategy/moves';
const money=(n:number)=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',notation:'compact',maximumFractionDigits:1}).format(n);
const labels={reach:'LPs reached',check:'Check size',baseline:'Baseline conversion',conversionLift:'Conversion lift (percentage points)',checkLift:'Check-size lift',confidence:'Effect discount',teamHours:'Team hours',cashCost:'Cash cost',effectDays:'Days to effect'};
export function MoveMenu({moves,vehicleId,ranks}:{moves:MoveRow[];vehicleId:string;ranks:Record<string,number>}) {
 return <section className="card strategy-moves" id="moves"><div className="chead"><h2>Strategic moves · {moves.length}</h2><ImportMoves /></div>
 <p className="cover">All estimates are GUESS scenarios, not commitments. Each vehicle has its own effect and decision. Alternatives can reach the same LPs: do not add their capital estimates or combine vehicles. Chosen means selected for planning; it authorizes no send, introduction, spend or publication.</p>
 {!moves.length&&<div className="cbody">No move records imported for this raise. Import the private menu to compare proposals.</div>}
 <div className="strategy-table-wrap"><table className="list strategy-compact"><thead><tr><th>Queue #</th><th>Move / evidence</th><th>Decision</th><th>GUESS $/hour</th><th>GUESS capital</th><th>GUESS hours</th><th>GUESS cost</th><th>GUESS days</th></tr></thead><tbody>{[...moves].sort((a,b)=>(ranks[a.id]??Infinity)-(ranks[b.id]??Infinity)).map(m=>{const score=moveScore(m.estimates);return <tr key={m.id} id={`move-${m.id}`}><td>{ranks[m.id]??'Dismissed'}</td><td><details><summary><b>{m.title}</b> <span className="muted">· {m.category}</span></summary><div className="move-detail"><p>{m.detail}</p><p><b>Vehicles:</b> {m.vehicles.join(' · ')}. Figures below apply only to this raise.</p><p><b>Audience:</b> {m.estimates.audience}</p><p><b>Dependencies:</b> {m.estimates.dependencies}</p><dl>{Object.entries(labels).map(([k,label])=>{const e=m.estimates[k as keyof typeof labels];return <div key={k}><dt>{label} · GUESS {['baseline','conversionLift','confidence'].includes(k)?`${(e.value*100).toFixed(1)}%`:['check','checkLift','cashCost'].includes(k)?money(e.value):e.value}</dt><dd>{e.basis}</dd></div>;})}</dl><p>Incremental capital = reach × [check × conversion lift + check-size lift × (baseline conversion + conversion lift)] × effect discount. Priority = incremental capital ÷ team hours. Cash cost and elapsed days are separate constraints.</p><h4>Evidence and limitations</h4>{m.evidence.map((e,i)=><p key={i}><b>{e.source}</b><br />As of {e.as_of} · {e.confidence} · last verified by {e.last_verified_by}<br />{e.supports}</p>)}<MoveControls key={`${m.id}:${m.version}`} move={m} vehicleId={vehicleId}/></div></details></td><td>{m.state}{m.position!==null&&<small> · manual #{m.position}</small>}</td><td>{money(score.priority)}</td><td>{money(score.expected)}</td><td>{m.estimates.teamHours.value}</td><td>{money(m.estimates.cashCost.value)}</td><td>{m.estimates.effectDays.value}</td></tr>;})}</tbody></table></div>
 </section>;
}
