import type { Action } from './index';
export type ScopeRule = 'context' | 'touch' | 'spvEntity' | 'signal' | 'global' | 'pursuit' | 'pursuitArg' | 'score' | 'bulk' | 'undo' | 'exposure' | 'suggestion' | 'play' | 'vehicleArg' | 'vehicle' | 'vehicleSlug' | 'move' | 'conflict' | 'tickets' | 'emailNew' | 'emailDraft' | 'self' | 'contentSend' | 'contentAsset';
/** Closed manifest: a new action needs an explicit policy AND a first-statement wrapper. */
export const actionRules = {
  'app/dev/linear/actions.ts#rebuildLinearAction': { action: 'admin', scope: 'global' },
  'app/dev/linear/actions.ts#linkProjectsAction': { action: 'admin', scope: 'global' },
  'app/[vehicle]/strategy/actions.ts#saveMove': { action: 'mutate', scope: 'move' },
  'app/[vehicle]/strategy/actions.ts#importMoveFile': { action: 'admin', scope: 'global' },
  'app/approvals/actions.ts#decide': { action: 'approve', scope: 'tickets' },
  'app/approvals/actions.ts#adjudicate': { action: 'mutate', scope: 'conflict' },
  'app/approvals/actions.ts#decideMany': { action: 'approve', scope: 'tickets' },
  // Agent tickets in a batch (5 Oct 2026): each checked ticket is checked as one decision would be.
  'app/approvals/actions.ts#decideAgentBatch': { action: 'approve', scope: 'tickets' },
  'app/dev/affinity/actions.ts#runConnectionTest': { action: 'admin', scope: 'global' },
  'app/dev/affinity/actions.ts#runDiscovery': { action: 'admin', scope: 'global' },
  'app/dev/affinity/actions.ts#runSliceAction': { action: 'admin', scope: 'global' },
  'app/dev/affinity/actions.ts#writeInventoryReport': { action: 'admin', scope: 'global' },
  'app/dev/affinity/actions.ts#writeMappingAction': { action: 'admin', scope: 'global' },
  'app/dev/affinity/actions.ts#writeComparisonAction': { action: 'admin', scope: 'global' },
  'app/dev/affinity/actions.ts#translateAction': { action: 'admin', scope: 'global' },
  'app/dev/affinity/actions.ts#countNotesAction': { action: 'admin', scope: 'global' },
  'app/dev/affinity/actions.ts#readNotesAction': { action: 'admin', scope: 'global' },
  'app/dev/affinity/actions.ts#readMeetingsAction': { action: 'admin', scope: 'global' },
  'app/dev/affinity/actions.ts#readHistoryAction': { action: 'admin', scope: 'global' },
  'app/dev/data/actions.ts#reloadInit': { action: 'admin', scope: 'global' },
  'app/dev/enrich/actions.ts#addProspectsAction': { action: 'admin', scope: 'global' },
  'app/dev/enrich/actions.ts#runWorkflowAction': { action: 'admin', scope: 'global' },
  'app/dev/enrich/actions.ts#runCloudFactCheckAction': { action: 'admin', scope: 'global' },
  'app/dev/enrich/actions.ts#runCloudProfileAction': { action: 'admin', scope: 'global' },
  'app/dev/enrich/actions.ts#runCloudStrategyAction': { action: 'admin', scope: 'global' },
  'app/dev/enrich/actions.ts#runCloudSourcingAction': { action: 'admin', scope: 'global' },
  'app/dev/enrich/actions.ts#exportResearchSetAction': { action: 'admin', scope: 'global' },
  'app/dev/enrich/actions.ts#importFindingsAction': { action: 'admin', scope: 'global' },
  'app/dev/enrich/actions.ts#sourceBulkAction': { action: 'admin', scope: 'global' },
  'app/dev/enrich/actions.ts#importPortfolioAction': { action: 'admin', scope: 'global' },
  'app/dev/enrich/actions.ts#importDakotaAction': { action: 'admin', scope: 'global' },
  'app/dev/enrich/actions.ts#consolidatePursuitsAction': { action: 'admin', scope: 'global' },
  'app/dev/enrich/actions.ts#reversePursuitMergeAction': { action: 'admin', scope: 'global' },
  'app/dev/enrich/actions.ts#mergeImportDuplicatesAction': { action: 'admin', scope: 'global' },
  'app/dev/enrich/actions.ts#reverseImportDuplicateAction': { action: 'admin', scope: 'global' },
  'app/dev/enrich/actions.ts#reverseIdentitySeparationAction': { action: 'admin', scope: 'global' },
  'app/dev/enrich/actions.ts#repointPursuitsAction': { action: 'admin', scope: 'global' },
  'app/dev/enrich/actions.ts#reverseLpRepointAction': { action: 'admin', scope: 'global' },
  'app/dev/enrich/actions.ts#deriveSpvStanceAction': { action: 'admin', scope: 'global' },
  'app/dev/linear/actions.ts#syncLinearAction': { action: 'admin', scope: 'global' },
  // Email drafts (docs/25): a draft is its owner's alone, and its vehicle comes from the record.
  'app/email/actions.ts#createDraftAction': { action: 'mutate', scope: 'emailNew' },
  'app/email/actions.ts#saveDraftAction': { action: 'mutate', scope: 'emailDraft' },
  'app/email/actions.ts#previewDraftAction': { action: 'read', scope: 'emailDraft' },
  'app/email/actions.ts#moveDraftAction': { action: 'mutate', scope: 'emailDraft' },
  'app/email/actions.ts#discardDraftAction': { action: 'mutate', scope: 'emailDraft' },
  'app/email/actions.ts#removeAttachmentAction': { action: 'mutate', scope: 'emailDraft' },
  'app/email/actions.ts#connectMailguardAction': { action: 'mutate', scope: 'self' },
  'app/email/actions.ts#testMailguardAction': { action: 'mutate', scope: 'self' },
  'app/email/actions.ts#forgetMailguardAction': { action: 'mutate', scope: 'self' },
  'app/email/actions.ts#demoMailguardAction': { action: 'mutate', scope: 'self' },
  // MCP tokens (docs/26): a person's own; the service revokes only the caller's.
  // Settings → Connections (docs/deploy/railway.md §3): Admin only; a refusal is audit-logged.
  'app/settings/connections/actions.ts#saveSettingAction': { action: 'admin', scope: 'global' },
  'app/settings/connections/actions.ts#clearSettingAction': { action: 'admin', scope: 'global' },
  'app/settings/connections/actions.ts#checkSettingAction': { action: 'admin', scope: 'global' },
  // Settings → People: the roster Google sign-in admits. Admin only; a refusal is audit-logged.
  'app/settings/people/actions.ts#addPersonAction': { action: 'admin', scope: 'global' },
  'app/settings/people/actions.ts#updatePersonAction': { action: 'admin', scope: 'global' },
  'app/settings/people/actions.ts#setPersonActiveAction': { action: 'admin', scope: 'global' },
  'app/settings/people/actions.ts#updateAddressesAction': { action: 'admin', scope: 'global' },
  'app/settings/people/actions.ts#signOutEverywhereAction': { action: 'admin', scope: 'global' },
  // Settings → Vehicles: an Admin adds a vehicle (the init file's row, made in the app). Admin, global; a refusal is audit-logged.
  'app/settings/vehicles/actions.ts#createVehicleAction': { action: 'admin', scope: 'global' },
  'app/settings/actions.ts#createMcpTokenAction': { action: 'mutate', scope: 'self' },
  'app/settings/actions.ts#revokeMcpTokenAction': { action: 'mutate', scope: 'self' },
  // Your own voice for drafts (docs/email-guidelines.md §Voice): only ever the caller's row.
  'app/settings/actions.ts#saveVoiceAction': { action: 'mutate', scope: 'self' },
  'app/grants/actions.ts#saveInvitation': { action: 'admin', scope: 'global' },
  'app/materials/actions.ts#proposeSend': { action: 'mutate', scope: 'vehicle' },
  // A person marks a cleared material sent (Juan, 5 Oct 2026: no SEND ticket for a person); its vehicle from the stored send.
  'app/materials/actions.ts#markSentAction': { action: 'mutate', scope: 'contentSend' },
  // A material's link (8 Oct 2026): its vehicle's members; a material for every vehicle needs all-vehicle access.
  'app/materials/actions.ts#setLinkAction': { action: 'mutate', scope: 'contentAsset' },
  'app/orgs/enrichment/select.ts#choose': { action: 'admin', scope: 'global' },
  'app/plays/actions.ts#assign': { action: 'mutate', scope: 'play' },
  'app/plays/actions.ts#propose': { action: 'mutate', scope: 'vehicleArg' },
  'app/routes/actions.ts#proposeFromRoute': { action: 'mutate', scope: 'vehicleSlug' },
  'app/routes/actions.ts#reviewEdgeAction': { action: 'mutate', scope: 'global' },
  'app/routes/actions.ts#buildNetworkAction': { action: 'admin', scope: 'global' },
  'app/selection/actions.ts#scoreDetailAction': { action: 'read', scope: 'score' },
  'app/selection/actions.ts#saveWeights': { action: 'admin', scope: 'global' },
  'app/signals-actions.ts#disposeSignal': { action: 'mutate', scope: 'signal' },
  'app/soft-hard/actions.ts#requestHarden': { action: 'mutate', scope: 'exposure' },
  'app/soft-hard/actions.ts#recordWire': { action: 'admin', scope: 'exposure' },
  'app/standup/pin.ts#pinToday': { action: 'mutate', scope: 'global' },
  'app/targets/actions.ts#requestLadderAdvance': { action: 'mutate', scope: 'pursuit' },
  'app/targets/actions.ts#setPursuitStatus': { action: 'mutate', scope: 'pursuit' },
  'app/targets/actions.ts#retractRungAction': { action: 'mutate', scope: 'pursuit' },
  'app/targets/actions.ts#addUpdateAction': { action: 'mutate', scope: 'pursuit' },
  'app/targets/actions.ts#addContextAction': { action: 'mutate', scope: 'context' },
  'app/targets/actions.ts#decideSuggestionAction': { action: 'mutate', scope: 'suggestion' },
  'app/targets/actions.ts#logTouchpointAction': { action: 'mutate', scope: 'touch' },
  'app/targets/actions.ts#closeTrackAction': { action: 'admin', scope: 'exposure' },
  'app/targets/actions.ts#decideReadingAction': { action: 'mutate', scope: 'global' },
  'app/targets/actions.ts#tagEventAction': { action: 'mutate', scope: 'global' },
  'app/targets/actions.ts#moveMetToDiscussing': { action: 'mutate', scope: 'pursuit' },
  'app/targets/bulk-actions.ts#bulkLpAction': { action: 'mutate', scope: 'bulk' },
  'app/targets/bulk-actions.ts#undoBulkLpAction': { action: 'mutate', scope: 'undo' },
  'app/targets/lp-unit-actions.ts#decideLpUnitAction': { action: 'mutate', scope: 'pursuitArg' },
  'app/targets/spv-actions.ts#setSpvStanceAction': { action: 'mutate', scope: 'spvEntity' },
  'app/targets/spv-actions.ts#withdrawSpvStanceAction': { action: 'mutate', scope: 'spvEntity' },
} as const satisfies Record<string, { action: Action; scope: ScopeRule }>;
export type ActionId = keyof typeof actionRules;
